### ISSUE TITLE
Add support for pixel window functions

### ISSUE THREAD

**Issue by chervias** [simonsobs/SOOPERCOOL#2]
We need to add pixel window functions since the observing by toast is done through TODs, so those filtered maps have a PWF.

**Comment by kwolz** [comment]
The transfer function compares TOAST-filtered simulations (which contain the pixel window function) to unfiltered simulations (which don't contain the PWF). The (mock) data are observed with the same TOAST filter. This means, the PWF is part of the map features that the transfer function approach is estimating empirically, hence we don't need to account for the PWF explicitly on the C_ell level. We verified this assumption with simulations.
