### ISSUE TITLE
`norm_nHits_SA_35FOV_ns512.fits` file

### ISSUE THREAD

**Issue by defjaf** [simonsobs/SOOPERCOOL#26]
I think there are two (separate?) issues with this file, needed to run the tests:

1. `pre_processer.py` is run first, and contains the line `hitmap = meta.read_hitmap()`. This presupposes the existence of the hitmap file, which is not downloaded until running `mask_handler.py`

2. In `mask_handler.py`, there is (I think) a typo:
```
    sat_nhits_file = f"{mask_dir}/norm_nHits_SA_35FOV_ns512.fits.fits"
```
rather than 
```
    sat_nhits_file = f"{mask_dir}/norm_nHits_SA_35FOV_ns512.fits"
```
Note the repeated `.fits.fits`!

But if you fix this typo and then move it into `../data/` with the correct name, the tests work.

**Comment by kwolz** [comment]
This has been addressed in [PR#23](https://github.com/simonsobs/SOOPERCOOL/pull/23).
