### ISSUE TITLE
Format the maps in the correct toast format

### ISSUE THREAD

**Issue by chervias** [simonsobs/SOOPERCOOL#3]
For simulated maps to be filtered by toast, we need to put them in the correct format. I think maps cannot be QU, they must be TQU, also the column_units in the header must have something otherwise toast will complain.

**Comment by damonge** [comment]
@chervias @adrien-laposta I think this is now addressed, right?

**Comment by kwolz** [comment]
All maps are now assumed to be TQU, so this part is addressed. We should add the column_units in the map header, as TOAST is still complaining about this.

**Comment by kwolz** [comment]
Done as TOAST filtering module has been successfully tested.
